USE CV;
CREATE TABLE CVdata (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nama VARCHAR(100) NOT NULL,
	alamat TEXT NOT NULL,
	telepon VARCHAR(20) NOT NULL,
	email VARCHAR(255) NOT NULL,
	web VARCHAR(255) NOT NULL, 
	pendidikan TEXT NOT NULL,
	SD TEXT NOT NULL,
	SMP TEXT NOT NULL,
	SMA TEXT NOT NULL,
	Kuliah TEXT NOT NULL,
	pengalaman_kerja TEXT NOT NULL,
	Software_System_Design TEXT NOT NULL,
	Staff_Design_Team TEXT NOT NULL,
	keterampilan TEXT NOT NULL,
	Teknis VARCHAR(255) NOT NULL,
	Lunak VARCHAR(255) NOT NULL,
	Bahasa VARCHAR(255) NOT NULL,
	foto_path VARCHAR(255) NOT NULL
);
SELECT*FROM CVdata;

